---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-traces.gatewayFullname" . }}
  labels:
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gateway.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.server.http_listen_port }}
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "enterprise-traces.gatewaySelectorLabels" . | nindent 4 }}
