apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-traces.adminApiFullname" . }}
  labels:
    {{- include "enterprise-traces.adminApiLabels" . | nindent 4 }}
    {{- with .Values.adminApi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.adminApi.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.server.http_listen_port }}
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: {{ .Values.server.grpc_listen_port }}
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "enterprise-traces.adminApiSelectorLabels" . | nindent 4 }}
