{{- if not .Values.useExternalLicense -}}
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-traces-license
  labels:
    {{- include "enterprise-traces.labels" . | nindent 4 }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
